spring:
  datasource:
    url: jdbc:mysql://8.129.217.148:3310/springbatch?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      schema:
        classpath:/org/springframework/batch/core/schema-mysql.sql
  batch:
    jdbc:
      initialize-schema: always
